# Benchmark configuration
# Lines starting with # are comments

# SSH connection
SshKey=C:\Users\vazois\.ssh\id_ed121824_notebook
SshUser=guser
SshHost=[vm0.eps8v6vmss.southcentralus.cloudapp.azure.com, vm0.dps8v6vmss.southcentralus.cloudapp.azure.com, vm0.dpls8v6vmss.southcentralus.cloudapp.azure.com]
SshCount=12
Multiplier=1

# Benchmark parameters
Host=10.5.1.4
Port=7000
Threads=16
Runtime=60
# DbSize=1000000
# KeyLength=16
# ValueLength=128
# BatchSize=100
ClusterBench=true

# Additional arguments (optional)
# ExtraArgs=--db-size 1000000
